### ISSUE TITLE
Postkarte aus Formular versenden

### ISSUE THREAD

**Issue by seppkurt** [spuckydaslama/elternbrief#12]
1. Nutzer stellt sich Text zusammen, Vorschau aktualisiert sich
2. Nutzer klickt auf Button "Als Postkarte versenden" (daneben gibt es die Option den Text auch anders zu teilen, anderer Button)
3. optional, falls nur ein Motiv vorhanden: Nutzer wählt Bildmotiv aus
4. Nutzer gibt _adresse_ in Formular ein
5. Nutzer klickt auf Absenden-Button
6. POST Request mit JSON _apikey, adresse, grusstext, bild_
6. Nutzer erhält Bestätigung das Absenden erfolgreich

_adresse_
    adresszeile1 (Empfänger)
    adresszeile2 (Zusatz)
    adresszeile3 (Straße Hausnummer)
    adresszeile4 (PLZ Stadt)
    adresszeile5 (Land)

**Comment by spuckydaslama** [comment]
So @seppkurt  sieht der payload im Zwischenspeicher aus pro Auftrag:
`{"grusstext":"Liebe \"Oma\"\n\nDa hab ich gedacht, ich frage dich mal, was dir so wichtig ist. Vielleicht kannst du ja ein bisschen für mich mit abstimmen.\nHier schreibt euch euer Enkelkind. In der Schule haben wir heute über die Wahlen im Herbst gesprochen. Alle Erwachsenen dürfen über eine neue Bundeskanzlerin abstimmen.\nErwachsen bin ich ja noch lange nicht, aber ich würde auch so gerne mitbestimmen. Es ist ja auch meine Zukunft.\n\n\nVielleicht können wir ja bei unserem nächsten Wiedersehen mal darüber sprechen, wie du entscheidest, wen du wählst. Ich möchte so gerne mehr darüber erfahren.\n\nSeid fest umarmt, Euer Enkelkind\n","adresse":{"adresszeile1":"Sonstewas","adresszeile2":"","adresszeile3":"A 10","adresszeile4":"14567 Leien","adresszeile5":"Deutschland"}}`

**Comment by seppkurt** [comment]
Payload an API Betreiber versandt

**Comment by seppkurt** [comment]
TXT gecheckt
