### ISSUE TITLE
Ausgabe des Brieftexts in "Textarea"

### ISSUE THREAD

**Issue by seppkurt** [spuckydaslama/elternbrief#13]
Der Nutzer, welcher den Brief zusammenstellt, möchte Detailanpassungen am Text vornehmen bevor dieser auf die Postkarte kommt. Wenn wir das Ergebnis des Formulars in ein "Textarea" einfügen, kann dies durch den Nutzers geschehen. 
Jede weitere Änderung im Formular überschreibt den Text im "Textarea".

**Comment by spuckydaslama** [comment]
@seppkurt 
1. einfach das aktuelle div mit einer textarea ersetzen meinst du, so dass man direkt bearbeiten kann?
2. Bearbeitungen gehen verloren sobald einer der Anpassungen aus dem anderen Formular geändert werden?

**Comment by seppkurt** [comment]
Ja und ja
