### ISSUE TITLE
Nutzer will Postkartenmotiv sehen

### ISSUE THREAD

**Issue by seppkurt** [spuckydaslama/elternbrief#14]
Wir stellen für die Postkarte ein Motiv (Bild) zur Verfügung. Der Nutzer soll dies beim Öffnen der Seite sehen. Dazu zeigen wir es 

- auf Desktop rechts neben dem Erklärtext oben an
- auf mobile unter dem Erklärtext, über dem Formular an

Falls Bild-Upload noch kommt, ist er daneben zu starten.

**Comment by spuckydaslama** [comment]
Könntest du beide Varianten(desktop, mobile) mockuppen, damit ich eine Vorstellung über die Verteilung des Platzes habe @seppkurt ?

**Comment by seppkurt** [comment]
![Screenshot 2021-09-02 10 17 46](https://user-images.githubusercontent.com/756643/131809050-448a0c16-c09d-4715-bde4-d6383efd6b2a.png)
![Screenshot 2021-09-02 10 16 08](https://user-images.githubusercontent.com/756643/131809054-fe89c464-0f41-45ab-bb2c-e82993678e2a.png)

auf desktop auf der rechten seite, für mobil zwischen dem erkärtext und dem formular

**Comment by seppkurt** [comment]
nicee! checked
