### ISSUE TITLE
Briefentwurf v1 in EBG integrieren

### ISSUE THREAD

**Issue by seppkurt** [spuckydaslama/elternbrief#2]
Hier https://docs.google.com/document/d/1hF3TkZmcYI2OHC_EcHgypOpOmJbxwS41bpORmPrHpew/edit#heading=h.c8zcjbejcegh liegt der erste Entwurf für einen vollständigen Brief. Diesen bitte mit Variablen in EBG integrieren.

Ziel: Als Nutzer der Seite möchte ich beim ersten Besuch direkt in der Lage sein einen Brief zusammenzustellen und diesen zu teilen.

**Comment by spuckydaslama** [comment]
Kannst du "teilen" spezifizieren @seppkurt.

**Comment by seppkurt** [comment]
Teilen = kopieren oder als PDF exportieren oder in WhatsApp einfügen
Also der Nutzer möchte einen fertigen Brief sehen
Reicht?

**Comment by spuckydaslama** [comment]
Willst du ein Feature oder muss der Text nur im Browser zu sehen sein? Wenn du ein Feature willst, welches dann?

**Comment by seppkurt** [comment]
Was meinst du mit Feature? Im Browser reicht
