### ISSUE TITLE
Umgestaltung des Textes mit Ziel Postkarte

### ISSUE THREAD

**Issue by seppkurt** [spuckydaslama/elternbrief#20]
Damit der Text besser auf die Karten und der Textfluss insgesamt runder passt und ist, habe ich das noch einmal frisch aufgesetzt.

Es gibt folgende Variablen 

- Grußformel Text, Bsp. Liebe Oma Traudel, Lieber Opa Horst!
- Erster Satz Text Bsp. Hier schreibt/en euch Leonie.
- Auswahl_Grund 1 aus 9 (Freitextoption ist einzig im Textfeld manuell einzupflegen)
- Auswahl_ letzer Satz 1 aus 3, die sind absichtlich etwas abgestuft in der Direktheit
- Abschiedsformel Text Bsp. Eure Leonie

Auswahlen siehe gdoc https://docs.google.com/document/d/1hF3TkZmcYI2OHC_EcHgypOpOmJbxwS41bpORmPrHpew/edit#heading=h.2otyv9k7207c

Es gibt keinen Bedarf mehr Einzahl und Mehrzahl zu unterscheiden.

Bitte keine Leerzeilen zwischen den Blöcken. Siehe Beispiel-Karte im Screenshot. Wir haben vermutlich sogar mehr Platz wegen Jumbo-Postkarte.

**Comment by seppkurt** [comment]
nice but ;-)

* Textzähler zählt viel zu wenig, kann der an falschen Variable hängen und nicht am Gesamttext?
* nach Einleitung und vor Grund kommt noch das Textschnippsel "Am 26.9. sind Wahlen. Alle Erwachsenen dürfen eine neue Regierung wählen. Meine Stimme ist nicht vertreten. Doch es geht es um meine Zukunft."
* Satzende Punkt hinter Einleitung bitte mit in die Vorgabe einfügen
* <Enkelkind> --> <Name-des/r-Kindes/r>
* Kann Einleitung einen Helptext erhalten? Dieser sollte sagen "Bitte <> mit dem Namen des/der Kindes/r ersetzen."
* Kann Abschied einen Helptext erhalten? Dieser sollte sagen "Bitte <> mit dem Namen des/der Kindes/r ersetzen."

**Comment by spuckydaslama** [comment]
- ich denke es wird richtig gezählt - deine Erwartungshaltung eventuell nicht getroffen? Da steht noch x von max y übrig. Vielleicht ist das irreführend?
- kann der Hilfetext wegfallen, wenn im Standard schon "Name des Enkels" steht?
-

**Comment by seppkurt** [comment]
Ach Mensch, Zähler zeigt ja die verbliebenen Zeichen an. Mein Fehler.. ;-)

**Comment by seppkurt** [comment]
Hilfetexte sollen ja erklären was da zu tun ist. Wenn der Inhalt der Variable mehr als der Name ist, sollte das schon erklärt werden

**Comment by spuckydaslama** [comment]
Mit dem Textschnipsel "Am 26.9. sind Wahlen. Alle Erwachsenen dürfen eine neue Regierung wählen. Meine Stimme ist nicht vertreten. Doch es geht es um meine Zukunft." sprengen wir in allen Varianten die 500 Zeichenmarke.

Wie gehen wir damit um @seppkurt ?

**Comment by seppkurt** [comment]
ja auch schon bemerkt, schaue ich mir an
