### ISSUE TITLE
SEO - Add Meta Description

### ISSUE THREAD

**Issue by spuckydaslama** [spuckydaslama/elternbrief#22]
https://web.dev/meta-description

Möchtest du eine schreiben @seppkurt ?

**Comment by seppkurt** [comment]
Bei Gelegenheit

**Comment by seppkurt** [comment]
<meta name="description" content="Kindern bei der BUndestagswahl eine Stimme geben. Erinnerung als Postkarte oder ähnliches an Großeltern, Familie und Bekannte verschicken.">

**Comment by spuckydaslama** [comment]
> _No description provided._

?? Du hast hier nichts geschrieben @seppkurt

**Comment by seppkurt** [comment]
argh, irgendwie nicht abgeschickt

<meta
  name="description"           
  content="Im Herbst sind Bundestagswahlen. Die Kinder haben wenig Einfluss darauf. Trotzdem geht es zu großen Teilen umihre Zukunft. Wir wollen ihnen eine Stimme verleihen indem wir für sie Postkarten an Großeltern, Tanten und Onkel versenden.">

**Comment by seppkurt** [comment]
wenn ich HTML Tags in den Kommentar einfüge, verschluckt er die, erneut...

html tags verschwinden im Quellcode und werden nicht gerendert

**Comment by seppkurt** [comment]
meta description
"Im Herbst sind Bundestagswahlen. Die Kinder haben wenig Einfluss darauf. Trotzdem geht es zu großen Teilen um ihre Zukunft. Wir wollen ihnen eine Stimme verleihen."

**Comment by spuckydaslama** [comment]
`<p> Benutzer 'Insert Code' dann kannst du auch solche Zeichen verwenden</p>`
