### ISSUE TITLE
Cookie less tracking of visitors

### ISSUE THREAD

**Issue by seppkurt** [spuckydaslama/elternbrief#36]
Als Team möchten wir wissen wie viele Besucher die Seite hat, um den Erfolg einordnen zu können.

**Comment by spuckydaslama** [comment]
Ohne personenbezogene Daten (Fingerprinting) oder serverside code (haben wir nicht für das ausliefern der statistischen Website) kenne ich keinen Weg eindeutig Besucher zu identifizieren. 
Wir müssen also auf page impressions gehen und anonyme Daten wie User agent (um bots zu filtern) usw. speichern.

Passt uns das fürs erste @seppkurt ?

**Comment by seppkurt** [comment]
da wir meines WIssens nach nur eine Seite haben, wären ja Page Impressions (ohne Neuladen) = Besuche. Falls das grob so ist, gern GO. Können ja mal die Realität anschauen was dabei rauskommt.

**Comment by spuckydaslama** [comment]
Mein Design wäre dann so.
PHP file schreiben, dass in eine Datei streamed und dort reinschreibt, was ich als payload mitgebe. Asynchron schickt der Client im Hintergrund dann einmal nen post request auf die php-file URL

**Comment by spuckydaslama** [comment]
Damit das hier ready for dev ist brauche ich mal wieder Zugang zu dem Host und Verzeichnissen wo wir stage und prod haben. @seppkurt

**Comment by spuckydaslama** [comment]
Done
