### ISSUE TITLE
Call-to-Action Bereich einbauen

### ISSUE THREAD

**Issue by seppkurt** [spuckydaslama/elternbrief#8]
Erstellen eines Briefes ist gut, aber es hilft nichts, wenn der Brief nicht weitergereicht wird. Daher:

**Als Nutzer möchte ich im Bereich unter dem fertigen Brief oder anders sichtbar das erstellte Ergebnis teilen können.**

Über das müssen wir "reden" erst einmal Entwurf
Aufgrund der Unterschiede zwischen den Geräten sollten wir auch das Teilen unterschiedlich anbieten.
1. mobil
   1.  wie kann man das Standard-Teilen des Smartphones einsetzen? Der Browser kann das. Daher Aufforderung dies darüber zu tun in der Form "Jetzt diesen Brief direkt am Telefon versenden"
   2. 
1. desktop
   1. E-Mail via mailto:-Link und Eingabe, gedacht für alle mit installiertem Mailclient
   2. interne Mailfunktion des Server (vermutlich brauchen wir da Captcha oder irgendwas was Spam verhindert)
   3. Button mit Label "Text kopieren", welcher den Text in die Zwischenablage des Geräts kopiert

**Comment by seppkurt** [comment]
oder wir setzen erst einmal Shariff ein https://github.com/heiseonline/shariff 
Twitter, Facebook, WhatsApp, Telegram, Mail

**Comment by spuckydaslama** [comment]
> oder wir setzen erst einmal Shariff ein https://github.com/heiseonline/shariff

Was wollen wir da teilen, die Webseite? Wenn ja, dann brauchen wir erstmal n Feature, dass ein Brief durch eine URL aufrufbar ist (da wir ja nur statische Seiten haben)

**Comment by spuckydaslama** [comment]
>    1. E-Mail via mailto:-Link und Eingabe, gedacht für alle mit installiertem Mailclient
Was soll in den Body der E-Mail? Das gleiche, was auch in die Zwischenablage kommen würde? Oder ein Link auf eine Webseite?

>    2. interne Mailfunktion des Server (vermutlich brauchen wir da Captcha oder irgendwas was Spam verhindert)
Gibt's ne Headless API - Wir haben ne statische Seite und dabei würde ich es so lange wie möglich belassen. Mehrwert finde ich begrenzt.

>    3. Button mit Label "Text kopieren", welcher den Text in die Zwischenablage des Geräts kopiert
:+1: 


> mobil
Gleiche Frage - Was soll geteilt werden können?

**Comment by seppkurt** [comment]
> > oder wir setzen erst einmal Shariff ein https://github.com/heiseonline/shariff
> 
> Was wollen wir da teilen, die Webseite? Wenn ja, dann brauchen wir erstmal n Feature, dass ein Brief durch eine URL aufrufbar ist (da wir ja nur statische Seiten haben)

Wir wollen aktuell den Text teilen.

**Comment by seppkurt** [comment]
>  >    1. E-Mail via mailto:-Link und Eingabe, gedacht für alle mit installiertem Mailclient
> Was soll in den Body der E-Mail? Das gleiche, was auch in die Zwischenablage kommen würde? Oder ein Link auf eine Webseite?
> 
> >    2. interne Mailfunktion des Server (vermutlich brauchen wir da Captcha oder irgendwas was Spam verhindert)
> Gibt's ne Headless API - Wir haben ne statische Seite und dabei würde ich es so lange wie möglich belassen. Mehrwert finde ich begrenzt.
> 
> >    3. Button mit Label "Text kopieren", welcher den Text in die Zwischenablage des Geräts kopiert
> :+1: 
> 
> 
> > mobil
> Gleiche Frage - Was soll geteilt werden können?
> 
> 
> 

Gleiche Antwort, Text (am besten mit Formatierung) teilen

**Comment by seppkurt** [comment]
> Gibt's ne Headless API - Wir haben ne statische Seite und dabei würde ich es so lange wie möglich belassen. Mehrwert finde ich begrenzt.

was meinst du damit?

**Comment by spuckydaslama** [comment]
> > Gibt's ne Headless API - Wir haben ne statische Seite und dabei würde ich es so lange wie möglich belassen. Mehrwert finde ich begrenzt.
> 
> was meinst du damit?

Für das Senden einer E-Mail brauchen wir serverside-code, nehme ich an, und im Moment haben wir das nicht, sondern ne statische Seite. Ich finde den Mehrwert schwach, dass unsere Seite direkt eine E-Mail sendet und würde es wegen schlechtem Aufwand-Nutzern-Verhältnis empfehlen nicht umzusetzen.

**Comment by spuckydaslama** [comment]
### Notizen
* https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by seppkurt** [comment]
Freigabe erteilt, ist schon cool :)
